// CAMERA REDUX
export const CAMERA_MODAL = 'CAMERA_MODAL'
export const CAMERA_SCAN_BARCODE = 'CAMERA_SCAN_BARCODE'

// PRODUCT REDUX
export const PRODUCT_MODAL = 'PRODUCT_MODAL'
export const PRODUCT_BACKGROUND_IMAGE = 'PRODUCT_BACKGROUND_IMAGE'
// SEARCH REDUX
export const SEARCH_MODAL = 'SEARCH_MODAL'

// PLACE REDUX (MAP)
export const PLACE_CONTENT = 'PLACE_CONTENT'

// PUSH REDUX
export const PUSH_ADD_PRODUCT = 'PUSH_ADD_PRODUCT'