// CAMERA REDUX
export const CAMERA_MODAL = 'CAMERA_MODAL'
export const CAMERA_SCAN_BARCODE = 'CAMERA_SCAN_BARCODE'

// PRODUCT REDUX
export const PRODUCT_MODAL = 'PRODUCT_MODAL'

// SEARCH REDUX
export const SEARCH_MODAL = 'SEARCH_MODAL'